name: delivery
services:
  delivery:
    build:
      target: development
      args:
        USER_ID: 1000
        GROUP_ID: 1000
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - ./:/app:cached
    working_dir: /app
    environment:
      PHP_XDEBUG: xdebug.so
      PHP_XDEBUG_MODE: debug
      PHP_XDEBUG_CLIENT_HOST: host.docker.internal
      PHP_XDEBUG_DISCOVER_CLIENT_HOST: false
      PHP_XDEBUG_IDEKEY: PHPSTORM
      PHP_XDEBUG_CLIENT_PORT: 9003
      PHP_XDEBUG_START_WITH_REQUEST: yes
